# Generated by Django 5.1.7 on 2025-03-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_patronymic"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="email"
            ),
        ),
    ]
