# Generated by Django 5.1.7 on 2025-03-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название учебного курса",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Введите описание учебного курса",
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
    ]
