# Generated by Django 5.1.7 on 2025-03-22 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликованность"),
        ),
        migrations.AddField(
            model_name="material",
            name="slug",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="человекочитаемая ссылка",
                max_length=200,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="views_count",
            field=models.ImageField(
                default=0,
                help_text="Введите количество просмотров",
                upload_to="",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
