# Generated by Django 5.1.7 on 2025-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_material_is_published_material_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="views_count",
            field=models.IntegerField(
                default=0,
                help_text="Введите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
